### ISSUE TITLE
Open the file which use Chinese Character as filename failed.

### ISSUE THREAD

**Issue by zw963** [hugopl/tijolo#13]
**Describe the bug**
Following are screenshots for describe my issue.

1. Open a file use `汉字` 作为文件名

![image](https://github.com/hugopl/tijolo/assets/549126/b3749ec3-b502-44c2-bf26-43fcf207a247)

----------------

2. Give a error dialog.

![image](https://github.com/hugopl/tijolo/assets/549126/1ad9deb4-158c-4493-8b3b-9c76acc2e50e)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - GTK Version: 
    gtk2 2.24.33-3
    gtk3 1:3.24.38-1
    gtk4 1:4.12.1-1

 - Version 0.7.4

**Additional context**

Some envs

export LANG=en_US.UTF-8
export LANGUAGE=en_US:en
export TZ='Asia/Shanghai'

LC_CTYPE was not set.

**Comment by zw963** [comment]
Hi, this issue get fix after test on 0.8.0, altough, it still not support the GB2312 encoding.

**Comment by hugopl** [comment]
Yeah, even the GtkSourceView supporting different encodings I'm only supporting UTF-8.

I'm not sure if I'll add support for different encodings in the future, but if so I may implement it in the easier way, i.e. translating the file to UTF-8 before opening it and re-translating it to the original encoding when saving it. All this because Crystal strings are always UTF-8 encoded, so handle strings in different encodings require some extra steps.

**Comment by hugopl** [comment]
I created an issue, so I don't forget about this https://github.com/hugopl/tijolo/issues/16

**Comment by hugopl** [comment]
Hi @zw963 , could you provide a sample file using GB2312 encoding? I have a branch here that is using `GtkSource::FileLoader` to load files instead of loading with Crystal code, so multiple encoding support can be supported.

If so, could you attach it to https://github.com/hugopl/tijolo/issues/16 ?
