### ISSUE TITLE
Running failed with GLib-GIO-ERROR, Settings schema 'io.github.hugopl.Tijolo' is not installed

### ISSUE THREAD

**Issue by zw963** [hugopl/tijolo#15]
Running failed after build successful.

```
 ╰─ $ bin/tijolo
Tijolo running 🚀️

(process:94082): GLib-GIO-ERROR **: 14:54:00.429: Settings schema 'io.github.hugopl.Tijolo' is not installed
```

Thanks.

**Comment by hugopl** [comment]
There's a ArchLinux package on AUR, did you tried it?
https://aur.archlinux.org/packages/tijolo

If not using the package, you need to tell glib to compile the gschema, bla bla... package manager does that automatically, but I added a Makefile target for this too.

Try
```
make post-install
```

It's on README, but now I think I should just put the commands there instead of trying to explain about Gtk stuff that doesn't matter for who is just installing the application.

**Comment by zw963** [comment]
Run `make post-install` works, thank you!
