### ISSUE TITLE
GTKSourceView4 requirement

### ISSUE THREAD

**Issue by megatux** [hugopl/tijolo#2]
**Describe the bug**
I'm on ElementaryOS 5.1 Hera, based on Ubuntu 18.04 LTS and I don't have the GTKSourceView4 devs packages. Is it possible to use the v3 somehow? Apparently, v4 packages conflicts with v3 so I can not install both versions.

**Comment by hugopl** [comment]
Hi,

Meanwhile Tijolo is almost compatible with both libraries, so it still possible to make it compile using GtkSourceView3 with not much changes in code, I did it and put in this branch https://github.com/hugopl/tijolo/tree/gtksourceview3 (not fully tested).

So you can create the deb package by running `./packages/make-ubuntu-package`

However I don't have plans to keep it working with both libraries, since when I start working on the language-server based auto completion and other stuff these changes will be bigger and just be harder to maintain for one person only.

Let me know if the branch worked for you.

**Comment by hugopl** [comment]
Ah, BTW on Archlinux both library versions can coexist (I have both installed here), so this could be just a packaging issue on Elementary OS.

**Comment by megatux** [comment]
Just tried it. Sorry the delay. No luck:

```
........
Building: tijolo
Error target tijolo failed to compile:
Showing last frame. Use --error-trace for full trace.

In lib/gobject/src/gobject.cr:29:9

 29 | {{run "gobject/generator/build_namespace", namespace, version}}
        ^--
Error: Error executing run (exit code: 1): gobject/generator/build_namespace GtkSource 3.0


stderr:

    Unhandled exception: Typelib file for namespace 'GtkSource', version '3.0' not found (Exception)
      from ???
      from ???
      from __crystal_main
      from main
      from __libc_start_main
      from _start
      from ???


make: *** [Makefile:4: all] Error 1

```

**Comment by hugopl** [comment]
You need the gir package for gtksource3, no idea how your distro packs it, on newer Ubuntu, for gtksourceview 4 the needed packages are:

- libgtksourceview-4-dev
- libgit2-dev
- libgirepository1.0-dev

So probably a `libgtksourceview-3-dev` should exist there.

**Comment by hugopl** [comment]
I installed the elementary docker image, I guess you should install:

`gir1.2-gtksource-3.0` and `libgtksourceview-3.0-dev`

**Comment by megatux** [comment]
I'm on Arch now mostly, so no more requirement for this :) . If you agree, we can close this issue.

**Comment by hugopl** [comment]
yes, and with GTK4 near to be released keep gtksourceview3 compatibility makes even less sense.

I use Arch too, so there are AUR packages for it that you can install using [yay](https://github.com/Jguer/yay):

 - https://aur.archlinux.org/packages/tijolo/
 - https://aur.archlinux.org/packages/tijolo-git/
