### ISSUE TITLE
Zoom in/out on editor (increase/decrease font size)

### ISSUE THREAD

**Issue by megatux** [hugopl/tijolo#4]
Is this issue related to this item on the TODO file?: 
> Ctrl+Shift+X "zoom" view.

**Comment by hugopl** [comment]
No, this "zoom" view is for when you have split views, i.e. showing 4 files at same time, then you want the current editor to "maximize" and show on entire screen instead of just 1/4 of the screen.

Increase/decrease font size should be easy to implement, probably I just didn't it already because I choose a default font size that works for me :laughing:.

I will try to add it on 0.3 on `Ctrl+=`/`Ctrl+-` to change the font size of current view (useful when sharing the screen over some video call) .... plus a config file entry to permanent change the font size.

Thanks for the feedback.
